# Generated by Django 3.2.4 on 2021-08-28 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='food_type',
            field=models.CharField(choices=[('Local Lishes', 'Local Dishes'), ('Fast Food', 'Fast Food'), ('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Soft Drink', 'Soft Drink'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='preparation_time',
            field=models.IntegerField(error_messages={'name': {'max_length': 'write only digit'}}, help_text='Time the food is expected to be ready in minutes(only digits)'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 8, 28, 6, 58, 48, 419118, tzinfo=utc)),
        ),
    ]
