# Generated by Django 3.2.4 on 2021-08-28 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20210828_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='food_type',
            field=models.CharField(choices=[('Local Lishes', 'Local Dishes'), ('Fast Food', 'Fast Food'), ('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Soft Drink', 'Soft Drink'), ('Others', 'Others')], default='Others', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 8, 28, 7, 0, 10, 195733, tzinfo=utc)),
        ),
    ]
